server:
  port: 8191
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Barnali2020/rentacar-config-store
          search-paths:
            - 'service-config/*service'  
  
